[project]
name = "pyxel-development"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyxel>=2.3.18",
    "ruff>=0.11.7",
]
